services:
  backend-flask:
    image: virenchav/backend:2.0.0  # Replace with your Docker Hub username
    ports:
      - "4000:4000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    networks:
      - app-network

  frontend:
    image: virenchav/frontend:2.0.0  # Replace with your Docker Hub username
    ports:
      - "80:80"
    depends_on:
      - backend-flask
    networks:
      - app-network

networks:
  app-network:
    driver: bridge